# Site settings
title: Hungry Bites
email: a.v.hermann@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Things I learn in my job as Software Engineer, Architect, CTO.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://blog.andyhermann.ch" # the base hostname & protocol for your site
twitter_username: andyhermann
github_username:  andreashermann

# Build settings
markdown: kramdown
